### PR TITLE
Fixing the double quotes problem

### PR DESCRIPTION
**Pull request by jefersonralmeida**
* fixing the double quotes problem

### CODE REVIEW

**Review by tomfor — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Can I be added to reviewers please?

**Review by czarpino — APPROVED** [review]
LGTM

**Comment by czarpino** [comment]
@piotroxp You should be able to review uninvited by going to the [diff view](https://github.com/codelathe/filecloudapi-php/pull/16/files) 😁

**Pull request merged**
